import 'package:flutter/material.dart';

ThemeData dark = ThemeData(
  fontFamily: 'TitilliumWeb',
  // primaryColor: Color(0xFF1B7FED),
  primaryColor: Color(0xFF0B4461),
  cardColor: null,
  canvasColor: null,
  //cursorColor: null,
  disabledColor: null,
  backgroundColor: null,
  applyElevationOverlayColor: null,
  bottomAppBarColor: null,
  dialogBackgroundColor: null,
  dividerColor: null,
  errorColor: null,
  focusColor: null,
  hoverColor: null,
  indicatorColor: null,
  primaryColorBrightness: null,
  colorScheme: null,
  colorSchemeSeed: null,
  primaryColorDark: null,
  primaryColorLight: null,
  scaffoldBackgroundColor: const Color(0xffBFBFBF),
  secondaryHeaderColor: null,
  selectedRowColor: null,
  shadowColor: null,
  splashColor: Color(0xffFFFFFF),
  toggleableActiveColor: null,
  unselectedWidgetColor: null,
  brightness: Brightness.dark,
  highlightColor: Color(0xFF252525),
  hintColor: Color(0xFFc7c7c7),
  pageTransitionsTheme: PageTransitionsTheme(builders: {
    TargetPlatform.android: ZoomPageTransitionsBuilder(),
    TargetPlatform.iOS: ZoomPageTransitionsBuilder(),
    TargetPlatform.fuchsia: ZoomPageTransitionsBuilder(),
  }),
);